export const positions = {
  id: 2,
  positions:
  [
  
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "1",
      "category": "",
      "device": "",
      "description": "Esošo sienu demontāža",
      "info": "",
      "unit": "m3",
      "quantity": 43.73,
      "quantity_": "",
      "timerate": 2.5,
      "workrate": 10,
      "jobsalary": 25,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 7.5,
      "meh_": "",
      "job_mat_meh": 32.5,
      "workload_sum": 109.325,
      "jobsalary_sum": 1093.25,
      "materials_sum": 0,
      "meh_sum": 327.98,
      "total": 1421.23,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "2",
      "category": "",
      "device": "",
      "description": "Esošo durvju demontāža",
      "info": "",
      "unit": "gb.",
      "quantity": 19,
      "quantity_": "",
      "timerate": 0.7,
      "workrate": 10,
      "jobsalary": 7,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 7.5,
      "workload_sum": 13.3,
      "jobsalary_sum": 133,
      "materials_sum": 0,
      "meh_sum": 9.5,
      "total": 142.5,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "3",
      "category": "",
      "device": "",
      "description": "Esošā sienu krāsojuma demontāža",
      "info": "",
      "unit": "m2",
      "quantity": 784.8,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 10,
      "jobsalary": 2,
      "jobsalary_": "",
      "materials": 0.35,
      "materials_": "",
      "meh": 0.25,
      "meh_": "",
      "job_mat_meh": 2.6,
      "workload_sum": 156.96,
      "jobsalary_sum": 1569.6,
      "materials_sum": 274.68,
      "meh_sum": 196.2,
      "total": 2040.48,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "4",
      "category": "",
      "device": "",
      "description": "Izlietnes demontāža",
      "info": "",
      "unit": "gb.",
      "quantity": 5,
      "quantity_": "",
      "timerate": 0.7,
      "workrate": 10,
      "jobsalary": 7,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 7.5,
      "workload_sum": 3.5,
      "jobsalary_sum": 35,
      "materials_sum": 0,
      "meh_sum": 2.5,
      "total": 37.5,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "5",
      "category": "",
      "device": "",
      "description": "Dušas demontāža",
      "info": "",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.5,
      "workrate": 10,
      "jobsalary": 5,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 5.5,
      "workload_sum": 1,
      "jobsalary_sum": 10,
      "materials_sum": 0,
      "meh_sum": 1,
      "total": 11,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "6",
      "category": "",
      "device": "",
      "description": "Tualetes poda demontāža",
      "info": "",
      "unit": "gb.",
      "quantity": 4,
      "quantity_": "",
      "timerate": 0.75,
      "workrate": 10,
      "jobsalary": 7.5,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 0.8,
      "meh_": "",
      "job_mat_meh": 8.3,
      "workload_sum": 3,
      "jobsalary_sum": 30,
      "materials_sum": 0,
      "meh_sum": 3.2,
      "total": 33.2,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "7",
      "category": "",
      "device": "",
      "description": "Esošā grīdas seguma demontāža",
      "info": "",
      "unit": "m2",
      "quantity": 372.05,
      "quantity_": "",
      "timerate": 0.65,
      "workrate": 10,
      "jobsalary": 6.5,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 0.75,
      "meh_": "",
      "job_mat_meh": 7.25,
      "workload_sum": 241.8325,
      "jobsalary_sum": 2418.33,
      "materials_sum": 0,
      "meh_sum": 279.04,
      "total": 2697.37,
      "total_": ""
    },
    {
      "SystemID": 1.1,
      "system": "Demontāžas darbi",
      "ID": "8",
      "category": "",
      "device": "",
      "description": "Būvgružu iznešana, izvešana un utilizācija",
      "info": "",
      "unit": "m3",
      "quantity": 100,
      "quantity_": "",
      "timerate": 1.25,
      "workrate": 10,
      "jobsalary": 12.5,
      "jobsalary_": "",
      "materials": 0,
      "materials_": "",
      "meh": 15.5,
      "meh_": "",
      "job_mat_meh": 28,
      "workload_sum": 125,
      "jobsalary_sum": 1250,
      "materials_sum": 0,
      "meh_sum": 1550,
      "total": 2800,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "1",
      "category": "Sienas tips 1",
      "device": "",
      "description": "Mitrumizturīgā ģipškartona montāža 2.kārtās 2x12,5mm",
      "info": "",
      "unit": "m2",
      "quantity": 26.5,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 2.28,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.88,
      "workload_sum": 3.975,
      "jobsalary_sum": 39.75,
      "materials_sum": 60.42,
      "meh_sum": 2.65,
      "total": 102.82,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "2",
      "category": "Sienas tips 2",
      "device": "",
      "description": "Skaņas izolācijas λD = 0,036 W/mK, akmens vate 50mm montāža",
      "info": "",
      "unit": "m2",
      "quantity": 13.25,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 1.55,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.15,
      "workload_sum": 1.9875,
      "jobsalary_sum": 19.88,
      "materials_sum": 20.54,
      "meh_sum": 1.33,
      "total": 41.75,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "3",
      "category": "Sienas tips 3",
      "device": "",
      "description": "Cinkota tērauda karkasa 50mm montāža",
      "info": "",
      "unit": "m2",
      "quantity": 13.25,
      "quantity_": "",
      "timerate": 0.73,
      "workrate": 10,
      "jobsalary": 7.3,
      "jobsalary_": "",
      "materials": 4.5,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 12.3,
      "workload_sum": 9.6725,
      "jobsalary_sum": 96.73,
      "materials_sum": 59.63,
      "meh_sum": 6.63,
      "total": 162.99,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "4",
      "category": "Sienas tips 4",
      "device": "",
      "description": "Mitrumizturīgā ģipškartona montāža 2.kārtās 2x12,5mm",
      "info": "",
      "unit": "m2",
      "quantity": 26.5,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 2.28,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.88,
      "workload_sum": 3.975,
      "jobsalary_sum": 39.75,
      "materials_sum": 60.42,
      "meh_sum": 2.65,
      "total": 102.82,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "5",
      "category": "Sienas tips 2",
      "device": "",
      "description": "Ģipškartona montāža 2.kārtās 2x12,5mm",
      "info": "",
      "unit": "m2",
      "quantity": 172.66,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 1.77,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.37,
      "workload_sum": 25.899,
      "jobsalary_sum": 258.99,
      "materials_sum": 305.61,
      "meh_sum": 17.27,
      "total": 581.87,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "6",
      "category": "Sienas tips 3",
      "device": "",
      "description": "Skaņas izolācijas λD = 0,036 W/mK, akmens vate 50mm montāža",
      "info": "",
      "unit": "m2",
      "quantity": 86.33,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 1.55,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.15,
      "workload_sum": 12.9495,
      "jobsalary_sum": 129.5,
      "materials_sum": 133.81,
      "meh_sum": 8.63,
      "total": 271.94,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "7",
      "category": "Sienas tips 4",
      "device": "",
      "description": "Cinkota tērauda karkasa 50mm montāža",
      "info": "",
      "unit": "m2",
      "quantity": 86.33,
      "quantity_": "",
      "timerate": 0.73,
      "workrate": 10,
      "jobsalary": 7.3,
      "jobsalary_": "",
      "materials": 4.5,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 12.3,
      "workload_sum": 63.0209,
      "jobsalary_sum": 630.21,
      "materials_sum": 388.49,
      "meh_sum": 43.17,
      "total": 1061.87,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "8",
      "category": "Sienas tips 5",
      "device": "",
      "description": "Ģipškartona montāža 2.kārtās 2x12,5mm",
      "info": "",
      "unit": "m2",
      "quantity": 172.66,
      "quantity_": "",
      "timerate": 0.15,
      "workrate": 10,
      "jobsalary": 1.5,
      "jobsalary_": "",
      "materials": 1.77,
      "materials_": "",
      "meh": 0.1,
      "meh_": "",
      "job_mat_meh": 3.37,
      "workload_sum": 25.899,
      "jobsalary_sum": 258.99,
      "materials_sum": 305.61,
      "meh_sum": 17.27,
      "total": 581.87,
      "total_": ""
    },
    {
      "SystemID": 1.2,
      "system": "Sienas",
      "ID": "9",
      "category": "Sienas tips 5",
      "device": "",
      "description": "Ķieģeļu sienas mūrēšana",
      "info": "",
      "unit": "m3",
      "quantity": 0.63,
      "quantity_": "",
      "timerate": 18,
      "workrate": 10,
      "jobsalary": 180,
      "jobsalary_": "",
      "materials": 256,
      "materials_": "",
      "meh": 22.5,
      "meh_": "",
      "job_mat_meh": 458.5,
      "workload_sum": 11.34,
      "jobsalary_sum": 113.4,
      "materials_sum": 161.28,
      "meh_sum": 14.18,
      "total": 288.86,
      "total_": ""
    },
    {
      "SystemID": 1.3,
      "system": "Grīdas",
      "ID": "1",
      "category": "Grīdas tips 1",
      "device": "",
      "description": "Izlīdzinošā slāņa izbūve Sakret FS vai ekvivalents 10mm biezumā",
      "info": "",
      "unit": "m2",
      "quantity": 166.45,
      "quantity_": "",
      "timerate": 0.42,
      "workrate": 10,
      "jobsalary": 4.2,
      "jobsalary_": "",
      "materials": 4,
      "materials_": "",
      "meh": 0.25,
      "meh_": "",
      "job_mat_meh": 8.45,
      "workload_sum": 69.909,
      "jobsalary_sum": 699.09,
      "materials_sum": 665.8,
      "meh_sum": 41.61,
      "total": 1406.5,
      "total_": ""
    },
    {
      "SystemID": 1.3,
      "system": "Grīdas",
      "ID": "2",
      "category": "Grīdas tips 2",
      "device": "",
      "description": "Izlīdzinošā slāņa izbūve Sakret FS vai ekvivalents 10mm biezumā",
      "info": "",
      "unit": "m2",
      "quantity": 205.6,
      "quantity_": "",
      "timerate": 0.42,
      "workrate": 10,
      "jobsalary": 4.2,
      "jobsalary_": "",
      "materials": 4,
      "materials_": "",
      "meh": 0.25,
      "meh_": "",
      "job_mat_meh": 8.45,
      "workload_sum": 86.352,
      "jobsalary_sum": 863.52,
      "materials_sum": 822.4,
      "meh_sum": 51.4,
      "total": 1737.32,
      "total_": ""
    },
    {
      "SystemID": 1.4,
      "system": "Logi, durvis",
      "ID": "1",
      "category": "Logi",
      "device": "",
      "description": "Bīdāma PVC loga L-01 montāža. Izmērs 2000x1000mm. ",
      "info": "",
      "unit": "gb",
      "quantity": 1,
      "quantity_": "",
      "timerate": 6.5,
      "workrate": 10,
      "jobsalary": 65,
      "jobsalary_": "",
      "materials": 215,
      "materials_": "",
      "meh": 15,
      "meh_": "",
      "job_mat_meh": 295,
      "workload_sum": 6.5,
      "jobsalary_sum": 65,
      "materials_sum": 215,
      "meh_sum": 15,
      "total": 295,
      "total_": ""
    },
    {
      "SystemID": 1.4,
      "system": "Logi, durvis",
      "ID": "2",
      "category": "Durvis",
      "device": "",
      "description": "Durvju D-01, 1000x2100mm (finierētas, vienviru durvis. Aprīkotas ar aizvērēju ar regulējamu spēku, slēdzeni, rokturi sudraba krāsā, rūdīta stiklojuma logu un metāla plāksni) izgatavošana, piegāde, montāža",
      "info": "",
      "unit": "gb",
      "quantity": 7,
      "quantity_": "",
      "timerate": 5.8,
      "workrate": 10,
      "jobsalary": 58,
      "jobsalary_": "",
      "materials": 195,
      "materials_": "",
      "meh": 5,
      "meh_": "",
      "job_mat_meh": 258,
      "workload_sum": 40.6,
      "jobsalary_sum": 406,
      "materials_sum": 1365,
      "meh_sum": 35,
      "total": 1806,
      "total_": ""
    },
    {
      "SystemID": 1.4,
      "system": "Logi, durvis",
      "ID": "3",
      "category": "Durvis",
      "device": "",
      "description": "Durvju D-02, 1000x2100mm (finierētas, vienviru durvis. Aprīkotas ar aizvērēju ar regulējamu spēku, slēdzeni, rokturi sudraba krāsā, metāla plāksni un ventilācijas resti) izgatavošana, piegāde, montāža",
      "info": "",
      "unit": "gb",
      "quantity": 3,
      "quantity_": "",
      "timerate": 5.8,
      "workrate": 10,
      "jobsalary": 58,
      "jobsalary_": "",
      "materials": 160,
      "materials_": "",
      "meh": 5,
      "meh_": "",
      "job_mat_meh": 223,
      "workload_sum": 17.4,
      "jobsalary_sum": 174,
      "materials_sum": 480,
      "meh_sum": 15,
      "total": 669,
      "total_": ""
    },
    {
      "SystemID": 1.4,
      "system": "Logi, durvis",
      "ID": "4",
      "category": "Durvis",
      "device": "",
      "description": "Durvju D-03, 800x2100mm (finierētas, vienviru durvis. Aprīkotas ar aizvērēju ar regulējamu spēku, slēdzeni, rokturi sudraba krāsā) izgatavošana, piegāde, montāža",
      "info": "",
      "unit": "gb",
      "quantity": 1,
      "quantity_": "",
      "timerate": 5.8,
      "workrate": 10,
      "jobsalary": 58,
      "jobsalary_": "",
      "materials": 146,
      "materials_": "",
      "meh": 5,
      "meh_": "",
      "job_mat_meh": 209,
      "workload_sum": 5.8,
      "jobsalary_sum": 58,
      "materials_sum": 146,
      "meh_sum": 5,
      "total": 209,
      "total_": ""
    },
    {
      "SystemID": 1.4,
      "system": "Logi, durvis",
      "ID": "5",
      "category": "Durvis",
      "device": "",
      "description": "Durvju D-04, 970x2100mm (finierētas, vienviru durvis. Aprīkotas ar aizvērēju ar regulējamu spēku, slēdzeni, rokturi sudraba krāsā) izgatavošana, piegāde, montāža",
      "info": "",
      "unit": "gb",
      "quantity": 1,
      "quantity_": "",
      "timerate": 5.8,
      "workrate": 10,
      "jobsalary": 58,
      "jobsalary_": "",
      "materials": 146,
      "materials_": "",
      "meh": 5,
      "meh_": "",
      "job_mat_meh": 209,
      "workload_sum": 5.8,
      "jobsalary_sum": 58,
      "materials_sum": 146,
      "meh_sum": 5,
      "total": 209,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "1",
      "category": "Griesti",
      "device": "",
      "description": "Šunveida iekārto alumīnija griestu CEIR vai ekvivalents montāža. Profila biezums 10mm, šūnas izmērs 100x100mm, profila augstums 40mm",
      "info": "",
      "unit": "m2",
      "quantity": 372.05,
      "quantity_": "",
      "timerate": 1.28,
      "workrate": 10,
      "jobsalary": 12.8,
      "jobsalary_": "",
      "materials": 24.65,
      "materials_": "",
      "meh": 1.1,
      "meh_": "",
      "job_mat_meh": 38.55,
      "workload_sum": 476.224,
      "jobsalary_sum": 4762.24,
      "materials_sum": 9171.03,
      "meh_sum": 409.26,
      "total": 14342.53,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "2",
      "category": "Sienas",
      "device": "",
      "description": "Esošās sienas izlīdzināšana",
      "info": "",
      "unit": "m2",
      "quantity": 784.8,
      "quantity_": "",
      "timerate": 1.15,
      "workrate": 10,
      "jobsalary": 11.5,
      "jobsalary_": "",
      "materials": 4.2,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 16.2,
      "workload_sum": 902.52,
      "jobsalary_sum": 9025.2,
      "materials_sum": 3296.16,
      "meh_sum": 392.4,
      "total": 12713.76,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "3",
      "category": "Sienas",
      "device": "",
      "description": "Sienu špaktelēšana, slīpēšana",
      "info": "",
      "unit": "m2",
      "quantity": 983.97,
      "quantity_": "",
      "timerate": 0.7,
      "workrate": 10,
      "jobsalary": 7,
      "jobsalary_": "",
      "materials": 2.05,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 9.55,
      "workload_sum": 688.779,
      "jobsalary_sum": 6887.79,
      "materials_sum": 2017.14,
      "meh_sum": 491.99,
      "total": 9396.92,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "4",
      "category": "Sienas",
      "device": "",
      "description": "Krāsojamās hidroizolācija ierīkošana 2.kārtās, t.sk., hidroizolācijas lenta stūros",
      "info": "",
      "unit": "m2",
      "quantity": 83.3,
      "quantity_": "",
      "timerate": 0.42,
      "workrate": 10,
      "jobsalary": 4.2,
      "jobsalary_": "",
      "materials": 9.5,
      "materials_": "",
      "meh": 0.25,
      "meh_": "",
      "job_mat_meh": 13.95,
      "workload_sum": 34.986,
      "jobsalary_sum": 349.86,
      "materials_sum": 791.35,
      "meh_sum": 20.83,
      "total": 1162.04,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "5",
      "category": "Sienas",
      "device": "",
      "description": "Sienu flīzēšana uz līmjavas kārtas un šuvošana. Keramiskās sienas flīzes \"Citizen\"/\"Citizen Blanco\" vai ekvivalents, izmērs 800x360mm",
      "info": "",
      "unit": "m2",
      "quantity": 83.3,
      "quantity_": "",
      "timerate": 1.8,
      "workrate": 10,
      "jobsalary": 18,
      "jobsalary_": "",
      "materials": 13.99,
      "materials_": "",
      "meh": 0.9,
      "meh_": "",
      "job_mat_meh": 32.89,
      "workload_sum": 149.94,
      "jobsalary_sum": 1499.4,
      "materials_sum": 1165.37,
      "meh_sum": 74.97,
      "total": 2739.74,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "6",
      "category": "Sienas",
      "device": "",
      "description": "Sienu gruntēšana un krāsošana ar mitrumizturīgu krāsu Sadolin Bindo vai ekvivalents 2.kārtās",
      "info": "",
      "unit": "m2",
      "quantity": 907.21,
      "quantity_": "",
      "timerate": 0.4,
      "workrate": 10,
      "jobsalary": 4,
      "jobsalary_": "",
      "materials": 2.05,
      "materials_": "",
      "meh": 0.3,
      "meh_": "",
      "job_mat_meh": 6.35,
      "workload_sum": 362.884,
      "jobsalary_sum": 3628.84,
      "materials_sum": 1859.78,
      "meh_sum": 272.16,
      "total": 5760.78,
      "total_": ""
    },
    {
      "SystemID": 1.5,
      "system": "Apdares darbi",
      "ID": "7",
      "category": "Grīdas",
      "device": "",
      "description": "Homogēna grīdas seguma Sphera vai ekvivalents montāža uz līmes kārtas. Seguma biezums 2mm, nodilumizturības klase 34, pretslīdes klase R9",
      "info": "",
      "unit": "m2",
      "quantity": 372.05,
      "quantity_": "",
      "timerate": 0.5,
      "workrate": 10,
      "jobsalary": 5,
      "jobsalary_": "",
      "materials": 17.3,
      "materials_": "",
      "meh": 0.6,
      "meh_": "",
      "job_mat_meh": 22.9,
      "workload_sum": 186.025,
      "jobsalary_sum": 1860.25,
      "materials_sum": 6436.47,
      "meh_sum": 223.23,
      "total": 8519.95,
      "total_": ""
    },
    {
      "SystemID": 1.6,
      "system": "Dažādi darbi",
      "ID": "",
      "category": "Klimata bloku nosegpaneļi",
      "device": "",
      "description": "Leņķprofila 80x80mm, b=6mm montāža. Krāsa pēc NCS kataloga NCS S 4020-R. L-01",
      "info": "",
      "unit": "m",
      "quantity": 7.8,
      "quantity_": "",
      "timerate": 0.65,
      "workrate": 10,
      "jobsalary": 6.5,
      "jobsalary_": "",
      "materials": 11.25,
      "materials_": "",
      "meh": 2.95,
      "meh_": "",
      "job_mat_meh": 20.7,
      "workload_sum": 5.07,
      "jobsalary_sum": 50.7,
      "materials_sum": 87.75,
      "meh_sum": 23.01,
      "total": 161.46,
      "total_": ""
    },
    {
      "SystemID": 1.6,
      "system": "Dažādi darbi",
      "ID": "",
      "category": "Klimata bloku nosegpaneļi",
      "device": "",
      "description": "Metāla elementa, platums 85mm, b=8mm montāža. Krāsa pēc NCS kataloga NCS S 4020-R. E-01",
      "info": "",
      "unit": "m",
      "quantity": 19.1,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 10,
      "jobsalary": 3.2,
      "jobsalary_": "",
      "materials": 9.25,
      "materials_": "",
      "meh": 2.5,
      "meh_": "",
      "job_mat_meh": 14.95,
      "workload_sum": 6.112,
      "jobsalary_sum": 61.12,
      "materials_sum": 176.68,
      "meh_sum": 47.75,
      "total": 285.55,
      "total_": ""
    },
    {
      "SystemID": 1.6,
      "system": "Dažādi darbi",
      "ID": "",
      "category": "Klimata bloku nosegpaneļi",
      "device": "",
      "description": "Impregnēta un antispetizēta koka konstrukcijas montāža. Krāsa pēc NCS kataloga NCS S 4020-R. K-01",
      "info": "",
      "unit": "m3",
      "quantity": 0.25,
      "quantity_": "",
      "timerate": 50,
      "workrate": 10,
      "jobsalary": 500,
      "jobsalary_": "",
      "materials": 285,
      "materials_": "",
      "meh": 50,
      "meh_": "",
      "job_mat_meh": 835,
      "workload_sum": 12.5,
      "jobsalary_sum": 125,
      "materials_sum": 71.25,
      "meh_sum": 12.5,
      "total": 208.75,
      "total_": ""
    },
    {
      "SystemID": 1.6,
      "system": "Dažādi darbi",
      "ID": "",
      "category": "Klimata bloku nosegpaneļi",
      "device": "",
      "description": "Skārda, b=0,5mm montāža. Krāsots ar pulverkrāsu. Krāsa pēc NCS kataloga NCS S 4020-R. J01",
      "info": "",
      "unit": "m2",
      "quantity": 4,
      "quantity_": "",
      "timerate": 1.5,
      "workrate": 10,
      "jobsalary": 15,
      "jobsalary_": "",
      "materials": 9.8,
      "materials_": "",
      "meh": 1.5,
      "meh_": "",
      "job_mat_meh": 26.3,
      "workload_sum": 6,
      "jobsalary_sum": 60,
      "materials_sum": 39.2,
      "meh_sum": 6,
      "total": 105.2,
      "total_": ""
    },
    {
      "SystemID": 1.6,
      "system": "Dažādi darbi",
      "ID": "",
      "category": "Klimata bloku nosegpaneļi",
      "device": "",
      "description": "Metāla stiprināšanas elementu montāža",
      "info": "",
      "unit": "gb",
      "quantity": 4,
      "quantity_": "",
      "timerate": 0.8,
      "workrate": 10,
      "jobsalary": 8,
      "jobsalary_": "",
      "materials": 12.5,
      "materials_": "",
      "meh": 0.5,
      "meh_": "",
      "job_mat_meh": 21,
      "workload_sum": 3.2,
      "jobsalary_sum": 32,
      "materials_sum": 50,
      "meh_sum": 2,
      "total": 84,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "1",
      "category": "APKURE",
      "device": "",
      "description": "Tērauda paneļu radiators COMPACT ar apakšu pieslēgumu, kplektā ar sienas stiprinājuma kronšteiniem, noslēgkorķi un atgaisotāju",
      "info": "CV22-300-800",
      "unit": "kpl.",
      "quantity": 10,
      "quantity_": "",
      "timerate": 1.1,
      "workrate": 17.5,
      "jobsalary": 19.25,
      "jobsalary_": "",
      "materials": 48.24,
      "materials_": "",
      "meh": 1.93,
      "meh_": "",
      "job_mat_meh": 69.42,
      "workload_sum": 11,
      "jobsalary_sum": 192.5,
      "materials_sum": 482.4,
      "meh_sum": 19.3,
      "total": 694.2,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "2",
      "category": "APKURE",
      "device": "",
      "description": "Tērauda paneļu radiators COMPACT ar apakšu pieslēgumu, kplektā ar sienas stiprinājuma kronšteiniem, noslēgkorķi un atgaisotāju",
      "info": "CV22-300-1200",
      "unit": "kpl.",
      "quantity": 11,
      "quantity_": "",
      "timerate": 1.2,
      "workrate": 17.5,
      "jobsalary": 21,
      "jobsalary_": "",
      "materials": 59.38,
      "materials_": "",
      "meh": 2.1,
      "meh_": "",
      "job_mat_meh": 82.48,
      "workload_sum": 13.2,
      "jobsalary_sum": 231,
      "materials_sum": 653.18,
      "meh_sum": 23.1,
      "total": 907.28,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "3",
      "category": "APKURE",
      "device": "",
      "description": "Radiatora noslēgvārsts ",
      "info": "RLV-K-15",
      "unit": "gb.",
      "quantity": 21,
      "quantity_": "",
      "timerate": 0.25,
      "workrate": 17.5,
      "jobsalary": 4.38,
      "jobsalary_": "",
      "materials": 14.58,
      "materials_": "",
      "meh": 0.44,
      "meh_": "",
      "job_mat_meh": 19.4,
      "workload_sum": 5.25,
      "jobsalary_sum": 91.98,
      "materials_sum": 306.18,
      "meh_sum": 9.24,
      "total": 407.4,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "4",
      "category": "APKURE",
      "device": "",
      "description": "Termostats",
      "info": "RA 2000",
      "unit": "gb.",
      "quantity": 21,
      "quantity_": "",
      "timerate": 0.05,
      "workrate": 17.5,
      "jobsalary": 0.88,
      "jobsalary_": "",
      "materials": 12.72,
      "materials_": "",
      "meh": 0.09,
      "meh_": "",
      "job_mat_meh": 13.69,
      "workload_sum": 1.05,
      "jobsalary_sum": 18.48,
      "materials_sum": 267.12,
      "meh_sum": 1.89,
      "total": 287.49,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "5",
      "category": "APKURE",
      "device": "",
      "description": "Mazoglekļa presējamā tērauda caurule",
      "info": "ø15",
      "unit": "m",
      "quantity": 182,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 0.96,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 4.81,
      "workload_sum": 36.4,
      "jobsalary_sum": 637,
      "materials_sum": 174.72,
      "meh_sum": 63.7,
      "total": 875.42,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "6",
      "category": "APKURE",
      "device": "",
      "description": "Mazoglekļa presējamā tērauda caurule",
      "info": "ø20",
      "unit": "m",
      "quantity": 6,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 1.29,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 5.14,
      "workload_sum": 1.2,
      "jobsalary_sum": 21,
      "materials_sum": 7.74,
      "meh_sum": 2.1,
      "total": 30.84,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "7",
      "category": "APKURE",
      "device": "",
      "description": "Mazoglekļa presējamā tērauda caurule",
      "info": "ø25",
      "unit": "m",
      "quantity": 40,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 1.68,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 5.53,
      "workload_sum": 8,
      "jobsalary_sum": 140,
      "materials_sum": 67.2,
      "meh_sum": 14,
      "total": 221.2,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "8",
      "category": "APKURE",
      "device": "",
      "description": "Cauruļu siltumizolācijas čaulas Ø19",
      "info": "TL-18/13-DG",
      "unit": "m",
      "quantity": 182,
      "quantity_": "",
      "timerate": 0.06,
      "workrate": 17.5,
      "jobsalary": 1.05,
      "jobsalary_": "",
      "materials": 0.47,
      "materials_": "",
      "meh": 0.11,
      "meh_": "",
      "job_mat_meh": 1.63,
      "workload_sum": 10.92,
      "jobsalary_sum": 191.1,
      "materials_sum": 85.54,
      "meh_sum": 20.02,
      "total": 296.66,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "9",
      "category": "APKURE",
      "device": "",
      "description": "Cauruļu siltumizolācijas čaulas Ø20",
      "info": "TL-22/13-DG",
      "unit": "m",
      "quantity": 6,
      "quantity_": "",
      "timerate": 0.06,
      "workrate": 17.5,
      "jobsalary": 1.05,
      "jobsalary_": "",
      "materials": 0.53,
      "materials_": "",
      "meh": 0.11,
      "meh_": "",
      "job_mat_meh": 1.69,
      "workload_sum": 0.36,
      "jobsalary_sum": 6.3,
      "materials_sum": 3.18,
      "meh_sum": 0.66,
      "total": 10.14,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "10",
      "category": "APKURE",
      "device": "",
      "description": "Cauruļu siltumizolācijas čaulas Ø25",
      "info": "TL-28/13-DG",
      "unit": "m",
      "quantity": 40,
      "quantity_": "",
      "timerate": 0.06,
      "workrate": 17.5,
      "jobsalary": 1.05,
      "jobsalary_": "",
      "materials": 0.62,
      "materials_": "",
      "meh": 0.11,
      "meh_": "",
      "job_mat_meh": 1.78,
      "workload_sum": 2.4,
      "jobsalary_sum": 42,
      "materials_sum": 24.8,
      "meh_sum": 4.4,
      "total": 71.2,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "11",
      "category": "APKURE",
      "device": "",
      "description": "Cauruļvadu fasondaļas",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 6.66,
      "workrate": 17.5,
      "jobsalary": 116.55,
      "jobsalary_": "",
      "materials": 499.32,
      "materials_": "",
      "meh": 11.66,
      "meh_": "",
      "job_mat_meh": 627.53,
      "workload_sum": 6.66,
      "jobsalary_sum": 116.55,
      "materials_sum": 499.32,
      "meh_sum": 11.66,
      "total": 627.53,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "12",
      "category": "APKURE",
      "device": "",
      "description": "Cauruļvadu stiprinājumi",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.76,
      "workrate": 17.5,
      "jobsalary": 30.8,
      "jobsalary_": "",
      "materials": 102.6,
      "materials_": "",
      "meh": 3.08,
      "meh_": "",
      "job_mat_meh": 136.48,
      "workload_sum": 1.76,
      "jobsalary_sum": 30.8,
      "materials_sum": 102.6,
      "meh_sum": 3.08,
      "total": 136.48,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "13",
      "category": "APKURE",
      "device": "",
      "description": "Montāžas palīgmateriāli",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 2.49,
      "workrate": 17.5,
      "jobsalary": 43.58,
      "jobsalary_": "",
      "materials": 145.5,
      "materials_": "",
      "meh": 4.36,
      "meh_": "",
      "job_mat_meh": 193.44,
      "workload_sum": 2.49,
      "jobsalary_sum": 43.58,
      "materials_sum": 145.5,
      "meh_sum": 4.36,
      "total": 193.44,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "14",
      "category": "APKURE",
      "device": "",
      "description": "Sistēmas marķēšanas materiāli",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 2.5,
      "workrate": 17.5,
      "jobsalary": 43.75,
      "jobsalary_": "",
      "materials": 75,
      "materials_": "",
      "meh": 4.38,
      "meh_": "",
      "job_mat_meh": 123.13,
      "workload_sum": 2.5,
      "jobsalary_sum": 43.75,
      "materials_sum": 75,
      "meh_sum": 4.38,
      "total": 123.13,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "15",
      "category": "APKURE",
      "device": "",
      "description": "Jaunu atvērumu veidošana un aizdare ar hermetizējošiem materiāliem",
      "info": "",
      "unit": "kpl.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 3.5,
      "workrate": 17.5,
      "jobsalary": 61.25,
      "jobsalary_": "",
      "materials": 25.64,
      "materials_": "",
      "meh": 6.13,
      "meh_": "",
      "job_mat_meh": 93.02,
      "workload_sum": 7,
      "jobsalary_sum": 122.5,
      "materials_sum": 51.28,
      "meh_sum": 12.26,
      "total": 186.04,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "16",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Ventilācijas iekārta PN1 komplektā ar vadības automātiku, ventilatoriem,šķērsplūsmas siltuma rekuperātoru, filtriem, sildīšanas  baterijai, motorizētiem vārstiem pie gaisa vadu izejām. Lp=1200 m3/h, Pp=200 Pa, Ln=1200m3/h, Pn=200 Pa",
      "info": "DUPLEX 1500 Multi",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 65,
      "workrate": 17.5,
      "jobsalary": 1137.5,
      "jobsalary_": "",
      "materials": 7072.16,
      "materials_": "",
      "meh": 113.75,
      "meh_": "",
      "job_mat_meh": 8323.41,
      "workload_sum": 65,
      "jobsalary_sum": 1137.5,
      "materials_sum": 7072.16,
      "meh_sum": 113.75,
      "total": 8323.41,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "17",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa ieņemšanas reste",
      "info": "RISD-420",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.4,
      "workrate": 17.5,
      "jobsalary": 24.5,
      "jobsalary_": "",
      "materials": 68.41,
      "materials_": "",
      "meh": 2.45,
      "meh_": "",
      "job_mat_meh": 95.36,
      "workload_sum": 1.4,
      "jobsalary_sum": 24.5,
      "materials_sum": 68.41,
      "meh_sum": 2.45,
      "total": 95.36,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "18",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa izmešanas reste",
      "info": "RISD-400",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.4,
      "workrate": 17.5,
      "jobsalary": 24.5,
      "jobsalary_": "",
      "materials": 68.41,
      "materials_": "",
      "meh": 2.45,
      "meh_": "",
      "job_mat_meh": 95.36,
      "workload_sum": 1.4,
      "jobsalary_sum": 24.5,
      "materials_sum": 68.41,
      "meh_sum": 2.45,
      "total": 95.36,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "19",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Trokšņu slāpētājs",
      "info": "SLU 50 200-300",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 1.4,
      "workrate": 17.5,
      "jobsalary": 24.5,
      "jobsalary_": "",
      "materials": 35,
      "materials_": "",
      "meh": 2.45,
      "meh_": "",
      "job_mat_meh": 61.95,
      "workload_sum": 2.8,
      "jobsalary_sum": 49,
      "materials_sum": 70,
      "meh_sum": 4.9,
      "total": 123.9,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "20",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Trokšņu slāpētājs",
      "info": "SLU 100 315-1200",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 1.4,
      "workrate": 17.5,
      "jobsalary": 24.5,
      "jobsalary_": "",
      "materials": 98,
      "materials_": "",
      "meh": 2.45,
      "meh_": "",
      "job_mat_meh": 124.95,
      "workload_sum": 2.8,
      "jobsalary_sum": 49,
      "materials_sum": 196,
      "meh_sum": 4.9,
      "total": 249.9,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "21",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Trokšņu slāpētājs",
      "info": "SLU 100 400-1200",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 1.4,
      "workrate": 17.5,
      "jobsalary": 24.5,
      "jobsalary_": "",
      "materials": 110,
      "materials_": "",
      "meh": 2.45,
      "meh_": "",
      "job_mat_meh": 136.95,
      "workload_sum": 2.8,
      "jobsalary_sum": 49,
      "materials_sum": 220,
      "meh_sum": 4.9,
      "total": 273.9,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "22",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Droseļvārsts",
      "info": "IRIS 125",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 9.78,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 15.94,
      "workload_sum": 0.32,
      "jobsalary_sum": 5.6,
      "materials_sum": 9.78,
      "meh_sum": 0.56,
      "total": 15.94,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "23",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Droseļvārsts",
      "info": "IRIS 250",
      "unit": "gb.",
      "quantity": 7,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 32.39,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 38.55,
      "workload_sum": 2.24,
      "jobsalary_sum": 39.2,
      "materials_sum": 226.73,
      "meh_sum": 3.92,
      "total": 269.85,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "24",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pieplūdes gaisa difuzors ar karbu",
      "info": "RHOB-250-2-6        +ATTD",
      "unit": "gb.",
      "quantity": 4,
      "quantity_": "",
      "timerate": 1.07,
      "workrate": 17.5,
      "jobsalary": 18.73,
      "jobsalary_": "",
      "materials": 122.07,
      "materials_": "",
      "meh": 1.87,
      "meh_": "",
      "job_mat_meh": 142.67,
      "workload_sum": 4.28,
      "jobsalary_sum": 74.92,
      "materials_sum": 488.28,
      "meh_sum": 7.48,
      "total": 570.68,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "25",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Nosūces gaisa difuzors ar karbu",
      "info": "HPKB-250-2-6        +ATTD",
      "unit": "gb.",
      "quantity": 3,
      "quantity_": "",
      "timerate": 1.07,
      "workrate": 17.5,
      "jobsalary": 18.73,
      "jobsalary_": "",
      "materials": 135.48,
      "materials_": "",
      "meh": 1.87,
      "meh_": "",
      "job_mat_meh": 156.08,
      "workload_sum": 3.21,
      "jobsalary_sum": 56.19,
      "materials_sum": 406.44,
      "meh_sum": 5.61,
      "total": 468.24,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "26",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Nosūces gaisa vārsts",
      "info": "KU 125",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 5.58,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 11.74,
      "workload_sum": 0.32,
      "jobsalary_sum": 5.6,
      "materials_sum": 5.58,
      "meh_sum": 0.56,
      "total": 11.74,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "27",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa vads no cinkota skārda",
      "info": "ø125",
      "unit": "m",
      "quantity": 6,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 2.14,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 10.81,
      "workload_sum": 2.7,
      "jobsalary_sum": 47.28,
      "materials_sum": 12.84,
      "meh_sum": 4.74,
      "total": 64.86,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "28",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa vads no cinkota skārda",
      "info": "ø250",
      "unit": "m",
      "quantity": 25,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 4.25,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 12.92,
      "workload_sum": 11.25,
      "jobsalary_sum": 197,
      "materials_sum": 106.25,
      "meh_sum": 19.75,
      "total": 323,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "29",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa vads no cinkota skārda",
      "info": "ø315",
      "unit": "m",
      "quantity": 18,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 5.77,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 14.44,
      "workload_sum": 8.1,
      "jobsalary_sum": 141.84,
      "materials_sum": 103.86,
      "meh_sum": 14.22,
      "total": 259.92,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "30",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa vads no cinkota skārda",
      "info": "ø400",
      "unit": "m",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 8.65,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 17.32,
      "workload_sum": 0.9,
      "jobsalary_sum": 15.76,
      "materials_sum": 17.3,
      "meh_sum": 1.58,
      "total": 34.64,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "31",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pagrieziens  90°",
      "info": "ø125",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 3.61,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 12.28,
      "workload_sum": 0.9,
      "jobsalary_sum": 15.76,
      "materials_sum": 7.22,
      "meh_sum": 1.58,
      "total": 24.56,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "32",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pagrieziens  90°",
      "info": "ø250",
      "unit": "gb.",
      "quantity": 3,
      "quantity_": "",
      "timerate": 0.45,
      "workrate": 17.5,
      "jobsalary": 7.88,
      "jobsalary_": "",
      "materials": 7.99,
      "materials_": "",
      "meh": 0.79,
      "meh_": "",
      "job_mat_meh": 16.66,
      "workload_sum": 1.35,
      "jobsalary_sum": 23.64,
      "materials_sum": 23.97,
      "meh_sum": 2.37,
      "total": 49.98,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "33",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pagrieziens  90°",
      "info": "ø400",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.55,
      "workrate": 17.5,
      "jobsalary": 9.63,
      "jobsalary_": "",
      "materials": 16.23,
      "materials_": "",
      "meh": 0.96,
      "meh_": "",
      "job_mat_meh": 26.82,
      "workload_sum": 1.1,
      "jobsalary_sum": 19.26,
      "materials_sum": 32.46,
      "meh_sum": 1.92,
      "total": 53.64,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "34",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pārēja ",
      "info": "ø250/ø200",
      "unit": "gb.",
      "quantity": 4,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 7.82,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 13.98,
      "workload_sum": 1.28,
      "jobsalary_sum": 22.4,
      "materials_sum": 31.28,
      "meh_sum": 2.24,
      "total": 55.92,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "35",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pārēja ",
      "info": "ø315/ø250",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 9.61,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 15.77,
      "workload_sum": 0.64,
      "jobsalary_sum": 11.2,
      "materials_sum": 19.22,
      "meh_sum": 1.12,
      "total": 31.54,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "36",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pārēja ",
      "info": "ø400/ø315",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.39,
      "workrate": 17.5,
      "jobsalary": 6.83,
      "jobsalary_": "",
      "materials": 14.9,
      "materials_": "",
      "meh": 0.68,
      "meh_": "",
      "job_mat_meh": 22.41,
      "workload_sum": 0.78,
      "jobsalary_sum": 13.66,
      "materials_sum": 29.8,
      "meh_sum": 1.36,
      "total": 44.82,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "37",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Pārēja ",
      "info": "ø500/ø400",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 0.47,
      "workrate": 17.5,
      "jobsalary": 8.23,
      "jobsalary_": "",
      "materials": 20.21,
      "materials_": "",
      "meh": 0.82,
      "meh_": "",
      "job_mat_meh": 29.26,
      "workload_sum": 0.94,
      "jobsalary_sum": 16.46,
      "materials_sum": 40.42,
      "meh_sum": 1.64,
      "total": 58.52,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "38",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Atzars",
      "info": "ø250/ø250",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 6.98,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 13.14,
      "workload_sum": 0.32,
      "jobsalary_sum": 5.6,
      "materials_sum": 6.98,
      "meh_sum": 0.56,
      "total": 13.14,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "39",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Atzars",
      "info": "ø315/ø250",
      "unit": "gb.",
      "quantity": 4,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 7.18,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 13.34,
      "workload_sum": 1.28,
      "jobsalary_sum": 22.4,
      "materials_sum": 28.72,
      "meh_sum": 2.24,
      "total": 53.36,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "40",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Atzars",
      "info": "ø315/ø125",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.32,
      "workrate": 17.5,
      "jobsalary": 5.6,
      "jobsalary_": "",
      "materials": 2.22,
      "materials_": "",
      "meh": 0.56,
      "meh_": "",
      "job_mat_meh": 8.38,
      "workload_sum": 0.32,
      "jobsalary_sum": 5.6,
      "materials_sum": 2.22,
      "meh_sum": 0.56,
      "total": 8.38,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "40.1.",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Siltumizolācijas paklājs b=20mm",
      "info": "",
      "unit": "m2",
      "quantity": 25,
      "quantity_": "",
      "timerate": 0.19,
      "workrate": 17.5,
      "jobsalary": 3.33,
      "jobsalary_": "",
      "materials": 3.35,
      "materials_": "",
      "meh": 0.33,
      "meh_": "",
      "job_mat_meh": 7.01,
      "workload_sum": 4.75,
      "jobsalary_sum": 83.25,
      "materials_sum": 83.75,
      "meh_sum": 8.25,
      "total": 175.25,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "41",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Siltumizolācijas paklājs b=50mm",
      "info": "",
      "unit": "m2",
      "quantity": 5,
      "quantity_": "",
      "timerate": 0.25,
      "workrate": 17.5,
      "jobsalary": 4.38,
      "jobsalary_": "",
      "materials": 5.59,
      "materials_": "",
      "meh": 0.44,
      "meh_": "",
      "job_mat_meh": 10.41,
      "workload_sum": 1.25,
      "jobsalary_sum": 21.9,
      "materials_sum": 27.95,
      "meh_sum": 2.2,
      "total": 52.05,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "42",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Elektroinstalācijas materiāli",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 9.52,
      "workrate": 17.5,
      "jobsalary": 166.6,
      "jobsalary_": "",
      "materials": 250,
      "materials_": "",
      "meh": 16.66,
      "meh_": "",
      "job_mat_meh": 433.26,
      "workload_sum": 9.52,
      "jobsalary_sum": 166.6,
      "materials_sum": 250,
      "meh_sum": 16.66,
      "total": 433.26,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "43",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Gaisa vadu stiprinājumi",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.52,
      "workrate": 17.5,
      "jobsalary": 9.1,
      "jobsalary_": "",
      "materials": 30.6,
      "materials_": "",
      "meh": 0.91,
      "meh_": "",
      "job_mat_meh": 40.61,
      "workload_sum": 0.52,
      "jobsalary_sum": 9.1,
      "materials_sum": 30.6,
      "meh_sum": 0.91,
      "total": 40.61,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "44",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Izolācijas stiprinājumi",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.67,
      "workrate": 17.5,
      "jobsalary": 11.73,
      "jobsalary_": "",
      "materials": 39.1,
      "materials_": "",
      "meh": 1.17,
      "meh_": "",
      "job_mat_meh": 52,
      "workload_sum": 0.67,
      "jobsalary_sum": 11.73,
      "materials_sum": 39.1,
      "meh_sum": 1.17,
      "total": 52,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "45",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Montāžas palīgmateriāli",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 2.21,
      "workrate": 17.5,
      "jobsalary": 38.68,
      "jobsalary_": "",
      "materials": 129,
      "materials_": "",
      "meh": 3.87,
      "meh_": "",
      "job_mat_meh": 171.55,
      "workload_sum": 2.21,
      "jobsalary_sum": 38.68,
      "materials_sum": 129,
      "meh_sum": 3.87,
      "total": 171.55,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "46",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Sistēmas marķēšanas materiāli",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 3.5,
      "workrate": 17.5,
      "jobsalary": 61.25,
      "jobsalary_": "",
      "materials": 100,
      "materials_": "",
      "meh": 6.13,
      "meh_": "",
      "job_mat_meh": 167.38,
      "workload_sum": 3.5,
      "jobsalary_sum": 61.25,
      "materials_sum": 100,
      "meh_sum": 6.13,
      "total": 167.38,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "47",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Tīrīšanas lūka",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 2,
      "workrate": 17.5,
      "jobsalary": 35,
      "jobsalary_": "",
      "materials": 64.5,
      "materials_": "",
      "meh": 3.5,
      "meh_": "",
      "job_mat_meh": 103,
      "workload_sum": 2,
      "jobsalary_sum": 35,
      "materials_sum": 64.5,
      "meh_sum": 3.5,
      "total": 103,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "48",
      "category": "VENTILĀCIJA",
      "device": "PN1",
      "description": "Jaunu atvērumu veidošana un aizdare ar hermetizējošiem materiāliem",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 23.6,
      "workrate": 17.5,
      "jobsalary": 413,
      "jobsalary_": "",
      "materials": 268.99,
      "materials_": "",
      "meh": 41.3,
      "meh_": "",
      "job_mat_meh": 723.29,
      "workload_sum": 23.6,
      "jobsalary_sum": 413,
      "materials_sum": 268.99,
      "meh_sum": 41.3,
      "total": 723.29,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "49",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "VRF- sistēmas ārējais bloks ar stiprinājumiem",
      "info": "RAS-12FSXNME",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 14.29,
      "workrate": 17.5,
      "jobsalary": 250.08,
      "jobsalary_": "",
      "materials": 5517.8,
      "materials_": "",
      "meh": 25.01,
      "meh_": "",
      "job_mat_meh": 5792.89,
      "workload_sum": 14.29,
      "jobsalary_sum": 250.08,
      "materials_sum": 5517.8,
      "meh_sum": 25.01,
      "total": 5792.89,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "50",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "VRF- sistēmas iekšējais bloks ar stiprinājumiem",
      "info": "RCIM-1.0FSN4E",
      "unit": "gb.",
      "quantity": 2,
      "quantity_": "",
      "timerate": 4.86,
      "workrate": 17.5,
      "jobsalary": 85.05,
      "jobsalary_": "",
      "materials": 468.63,
      "materials_": "",
      "meh": 8.51,
      "meh_": "",
      "job_mat_meh": 562.19,
      "workload_sum": 9.72,
      "jobsalary_sum": 170.1,
      "materials_sum": 937.26,
      "meh_sum": 17.02,
      "total": 1124.38,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "51",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "VRF- sistēmas iekšējais bloks ar stiprinājumiem",
      "info": "RCIM-1.5FSN4E",
      "unit": "gb.",
      "quantity": 5,
      "quantity_": "",
      "timerate": 4.86,
      "workrate": 17.5,
      "jobsalary": 85.05,
      "jobsalary_": "",
      "materials": 474.38,
      "materials_": "",
      "meh": 8.51,
      "meh_": "",
      "job_mat_meh": 567.94,
      "workload_sum": 24.3,
      "jobsalary_sum": 425.25,
      "materials_sum": 2371.9,
      "meh_sum": 42.55,
      "total": 2839.7,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "52",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "VRF- sistēmas PN1 pievienošanas komplekts",
      "info": "EXV-3.0E2",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 6.2,
      "workrate": 17.5,
      "jobsalary": 108.5,
      "jobsalary_": "",
      "materials": 500.53,
      "materials_": "",
      "meh": 10.85,
      "meh_": "",
      "job_mat_meh": 619.88,
      "workload_sum": 6.2,
      "jobsalary_sum": 108.5,
      "materials_sum": 500.53,
      "meh_sum": 10.85,
      "total": 619.88,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "53",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Kasešu kondicioniera dekoratīvs panelis",
      "info": "P-AP56NAM",
      "unit": "gb.",
      "quantity": 7,
      "quantity_": "",
      "timerate": 2.63,
      "workrate": 17.5,
      "jobsalary": 46.03,
      "jobsalary_": "",
      "materials": 153.24,
      "materials_": "",
      "meh": 4.6,
      "meh_": "",
      "job_mat_meh": 203.87,
      "workload_sum": 18.41,
      "jobsalary_sum": 322.21,
      "materials_sum": 1072.68,
      "meh_sum": 32.2,
      "total": 1427.09,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "54",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Vadības pults",
      "info": "PC-AWR",
      "unit": "gb.",
      "quantity": 7,
      "quantity_": "",
      "timerate": 1.47,
      "workrate": 17.5,
      "jobsalary": 25.73,
      "jobsalary_": "",
      "materials": 85.66,
      "materials_": "",
      "meh": 2.57,
      "meh_": "",
      "job_mat_meh": 113.96,
      "workload_sum": 10.29,
      "jobsalary_sum": 180.11,
      "materials_sum": 599.62,
      "meh_sum": 17.99,
      "total": 797.72,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "55",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "kplekts bezvadu tālvadībai (uz paneļa)",
      "info": "PC-ALHC1",
      "unit": "gb.",
      "quantity": 7,
      "quantity_": "",
      "timerate": 1.8,
      "workrate": 17.5,
      "jobsalary": 31.5,
      "jobsalary_": "",
      "materials": 105.05,
      "materials_": "",
      "meh": 3.15,
      "meh_": "",
      "job_mat_meh": 139.7,
      "workload_sum": 12.6,
      "jobsalary_sum": 220.5,
      "materials_sum": 735.35,
      "meh_sum": 22.05,
      "total": 977.9,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "56",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Vadības pults ar taimeru",
      "info": "PC-ARFP1E",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.36,
      "workrate": 17.5,
      "jobsalary": 23.8,
      "jobsalary_": "",
      "materials": 79.16,
      "materials_": "",
      "meh": 2.38,
      "meh_": "",
      "job_mat_meh": 105.34,
      "workload_sum": 1.36,
      "jobsalary_sum": 23.8,
      "materials_sum": 79.16,
      "meh_sum": 2.38,
      "total": 105.34,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "57",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Atzars",
      "info": "E-162SN4",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.68,
      "workrate": 17.5,
      "jobsalary": 11.9,
      "jobsalary_": "",
      "materials": 39.49,
      "materials_": "",
      "meh": 1.19,
      "meh_": "",
      "job_mat_meh": 52.58,
      "workload_sum": 0.68,
      "jobsalary_sum": 11.9,
      "materials_sum": 39.49,
      "meh_sum": 1.19,
      "total": 52.58,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "58",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Atzars",
      "info": "E-102SN4",
      "unit": "gb.",
      "quantity": 6,
      "quantity_": "",
      "timerate": 0.54,
      "workrate": 17.5,
      "jobsalary": 9.45,
      "jobsalary_": "",
      "materials": 31.59,
      "materials_": "",
      "meh": 0.95,
      "meh_": "",
      "job_mat_meh": 41.99,
      "workload_sum": 3.24,
      "jobsalary_sum": 56.7,
      "materials_sum": 189.54,
      "meh_sum": 5.7,
      "total": 251.94,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "59",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīiciski izolēta freona caurule Ø6.35",
      "info": "",
      "unit": "m",
      "quantity": 10,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 1.39,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 5.24,
      "workload_sum": 2,
      "jobsalary_sum": 35,
      "materials_sum": 13.9,
      "meh_sum": 3.5,
      "total": 52.4,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "60",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīiciski izolēta freona caurule Ø9.52",
      "info": "",
      "unit": "m",
      "quantity": 30,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 2.6,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 6.45,
      "workload_sum": 6,
      "jobsalary_sum": 105,
      "materials_sum": 78,
      "meh_sum": 10.5,
      "total": 193.5,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "61",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīiciski izolēta freona caurule Ø12.7",
      "info": "",
      "unit": "m",
      "quantity": 20,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 2.19,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 6.04,
      "workload_sum": 4,
      "jobsalary_sum": 70,
      "materials_sum": 43.8,
      "meh_sum": 7,
      "total": 120.8,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "62",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīiciski izolēta freona caurule Ø15.88",
      "info": "",
      "unit": "m",
      "quantity": 30,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 3.21,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 7.06,
      "workload_sum": 6,
      "jobsalary_sum": 105,
      "materials_sum": 96.3,
      "meh_sum": 10.5,
      "total": 211.8,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "63",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīciski izolēta freona caurule Ø19.05",
      "info": "",
      "unit": "m",
      "quantity": 5,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 5.85,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 9.7,
      "workload_sum": 1,
      "jobsalary_sum": 17.5,
      "materials_sum": 29.25,
      "meh_sum": 1.75,
      "total": 48.5,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "64",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Rūpnīciski izolēta freona caurule Ø25.4",
      "info": "",
      "unit": "m",
      "quantity": 10,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 11.42,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 15.27,
      "workload_sum": 2,
      "jobsalary_sum": 35,
      "materials_sum": 114.2,
      "meh_sum": 3.5,
      "total": 152.7,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "65",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Kondensata caurule     Ø32",
      "info": "",
      "unit": "m",
      "quantity": 70,
      "quantity_": "",
      "timerate": 0.17,
      "workrate": 17.5,
      "jobsalary": 2.98,
      "jobsalary_": "",
      "materials": 0.85,
      "materials_": "",
      "meh": 0.3,
      "meh_": "",
      "job_mat_meh": 4.13,
      "workload_sum": 11.9,
      "jobsalary_sum": 208.6,
      "materials_sum": 59.5,
      "meh_sum": 21,
      "total": 289.1,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "66",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Freons",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.02,
      "workrate": 17.5,
      "jobsalary": 17.85,
      "jobsalary_": "",
      "materials": 765,
      "materials_": "",
      "meh": 1.79,
      "meh_": "",
      "job_mat_meh": 784.64,
      "workload_sum": 1.02,
      "jobsalary_sum": 17.85,
      "materials_sum": 765,
      "meh_sum": 1.79,
      "total": 784.64,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "67",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Cauruļu stiprinājumi",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.35,
      "workrate": 17.5,
      "jobsalary": 23.63,
      "jobsalary_": "",
      "materials": 78.75,
      "materials_": "",
      "meh": 2.36,
      "meh_": "",
      "job_mat_meh": 104.74,
      "workload_sum": 1.35,
      "jobsalary_sum": 23.63,
      "materials_sum": 78.75,
      "meh_sum": 2.36,
      "total": 104.74,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "68",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Montāžas palīgmateriāli",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 3.65,
      "workrate": 17.5,
      "jobsalary": 63.88,
      "jobsalary_": "",
      "materials": 213,
      "materials_": "",
      "meh": 6.39,
      "meh_": "",
      "job_mat_meh": 283.27,
      "workload_sum": 3.65,
      "jobsalary_sum": 63.88,
      "materials_sum": 213,
      "meh_sum": 6.39,
      "total": 283.27,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "69",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Sistēmas marķēšanas materiāli",
      "info": "",
      "unit": "kpl.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 3.5,
      "workrate": 17.5,
      "jobsalary": 61.25,
      "jobsalary_": "",
      "materials": 100,
      "materials_": "",
      "meh": 6.13,
      "meh_": "",
      "job_mat_meh": 167.38,
      "workload_sum": 3.5,
      "jobsalary_sum": 61.25,
      "materials_sum": 100,
      "meh_sum": 6.13,
      "total": 167.38,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "70",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Jaunu atvērumu veidošana un aizdare ar hermetizējošiem materiāliem",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 24.27,
      "workrate": 17.5,
      "jobsalary": 424.73,
      "jobsalary_": "",
      "materials": 215.6,
      "materials_": "",
      "meh": 42.47,
      "meh_": "",
      "job_mat_meh": 682.8,
      "workload_sum": 24.27,
      "jobsalary_sum": 424.73,
      "materials_sum": 215.6,
      "meh_sum": 42.47,
      "total": 682.8,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "71",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K1",
      "description": "Elektrokomutācijas kabeļi",
      "info": "",
      "unit": "kpl",
      "quantity": 1,
      "quantity_": "",
      "timerate": 20.19,
      "workrate": 17.5,
      "jobsalary": 353.33,
      "jobsalary_": "",
      "materials": 530,
      "materials_": "",
      "meh": 35.33,
      "meh_": "",
      "job_mat_meh": 918.66,
      "workload_sum": 20.19,
      "jobsalary_sum": 353.33,
      "materials_sum": 530,
      "meh_sum": 35.33,
      "total": 918.66,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "72",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "VRF- sistēmas ārējais bloks ar stiprinājumiem",
      "info": "RAS-12FSXNME",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 14.29,
      "workrate": 17.5,
      "jobsalary": 250.08,
      "jobsalary_": "",
      "materials": 5517.8,
      "materials_": "",
      "meh": 25.01,
      "meh_": "",
      "job_mat_meh": 5792.89,
      "workload_sum": 14.29,
      "jobsalary_sum": 250.08,
      "materials_sum": 5517.8,
      "meh_sum": 25.01,
      "total": 5792.89,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "73",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "VRF- sistēmas iekšējais bloks ar stiprinājumiem",
      "info": "RCIM-0.4FSN4E",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 4.86,
      "workrate": 17.5,
      "jobsalary": 85.05,
      "jobsalary_": "",
      "materials": 416.88,
      "materials_": "",
      "meh": 8.51,
      "meh_": "",
      "job_mat_meh": 510.44,
      "workload_sum": 4.86,
      "jobsalary_sum": 85.05,
      "materials_sum": 416.88,
      "meh_sum": 8.51,
      "total": 510.44,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "74",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "VRF- sistēmas iekšējais bloks ar stiprinājumiem",
      "info": "RCIM-1.0FSN4E",
      "unit": "gb.",
      "quantity": 8,
      "quantity_": "",
      "timerate": 4.86,
      "workrate": 17.5,
      "jobsalary": 85.05,
      "jobsalary_": "",
      "materials": 468.63,
      "materials_": "",
      "meh": 8.51,
      "meh_": "",
      "job_mat_meh": 562.19,
      "workload_sum": 38.88,
      "jobsalary_sum": 680.4,
      "materials_sum": 3749.04,
      "meh_sum": 68.08,
      "total": 4497.52,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "75",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "VRF- sistēmas PN2 pievienošanas kplekts",
      "info": "noslēgvārsti 9.52/15.88)",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.43,
      "workrate": 17.5,
      "jobsalary": 7.53,
      "jobsalary_": "",
      "materials": 36.51,
      "materials_": "",
      "meh": 0.75,
      "meh_": "",
      "job_mat_meh": 44.79,
      "workload_sum": 0.43,
      "jobsalary_sum": 7.53,
      "materials_sum": 36.51,
      "meh_sum": 0.75,
      "total": 44.79,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "76",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Kasešu kondicioniera dekoratīvs panelis",
      "info": "P-AP56NAM",
      "unit": "gb.",
      "quantity": 9,
      "quantity_": "",
      "timerate": 2.63,
      "workrate": 17.5,
      "jobsalary": 46.03,
      "jobsalary_": "",
      "materials": 153.24,
      "materials_": "",
      "meh": 4.6,
      "meh_": "",
      "job_mat_meh": 203.87,
      "workload_sum": 23.67,
      "jobsalary_sum": 414.27,
      "materials_sum": 1379.16,
      "meh_sum": 41.4,
      "total": 1834.83,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "77",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Vadības pults",
      "info": "PC-AWR",
      "unit": "gb.",
      "quantity": 9,
      "quantity_": "",
      "timerate": 1.47,
      "workrate": 17.5,
      "jobsalary": 25.73,
      "jobsalary_": "",
      "materials": 85.66,
      "materials_": "",
      "meh": 2.57,
      "meh_": "",
      "job_mat_meh": 113.96,
      "workload_sum": 13.23,
      "jobsalary_sum": 231.57,
      "materials_sum": 770.94,
      "meh_sum": 23.13,
      "total": 1025.64,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "78",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "kplekts bezvadu tālvadībai (uz paneļa)",
      "info": "PC-ALHC1",
      "unit": "gb.",
      "quantity": 9,
      "quantity_": "",
      "timerate": 1.8,
      "workrate": 17.5,
      "jobsalary": 31.5,
      "jobsalary_": "",
      "materials": 105.05,
      "materials_": "",
      "meh": 3.15,
      "meh_": "",
      "job_mat_meh": 139.7,
      "workload_sum": 16.2,
      "jobsalary_sum": 283.5,
      "materials_sum": 945.45,
      "meh_sum": 28.35,
      "total": 1257.3,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "79",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Vadības pults ar taimeru",
      "info": "PC-ARFP1E",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 1.36,
      "workrate": 17.5,
      "jobsalary": 23.8,
      "jobsalary_": "",
      "materials": 79.16,
      "materials_": "",
      "meh": 2.38,
      "meh_": "",
      "job_mat_meh": 105.34,
      "workload_sum": 1.36,
      "jobsalary_sum": 23.8,
      "materials_sum": 79.16,
      "meh_sum": 2.38,
      "total": 105.34,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "80",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Atzars",
      "info": "E-162SN4",
      "unit": "gb.",
      "quantity": 1,
      "quantity_": "",
      "timerate": 0.68,
      "workrate": 17.5,
      "jobsalary": 11.9,
      "jobsalary_": "",
      "materials": 39.49,
      "materials_": "",
      "meh": 1.19,
      "meh_": "",
      "job_mat_meh": 52.58,
      "workload_sum": 0.68,
      "jobsalary_sum": 11.9,
      "materials_sum": 39.49,
      "meh_sum": 1.19,
      "total": 52.58,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "81",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Atzars",
      "info": "E-102SN4",
      "unit": "gb.",
      "quantity": 8,
      "quantity_": "",
      "timerate": 0.54,
      "workrate": 17.5,
      "jobsalary": 9.45,
      "jobsalary_": "",
      "materials": 31.59,
      "materials_": "",
      "meh": 0.95,
      "meh_": "",
      "job_mat_meh": 41.99,
      "workload_sum": 4.32,
      "jobsalary_sum": 75.6,
      "materials_sum": 252.72,
      "meh_sum": 7.6,
      "total": 335.92,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "82",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Rūpnīiciski izolēta freona caurule Ø6.35",
      "info": "",
      "unit": "m",
      "quantity": 10,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 1.39,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 5.24,
      "workload_sum": 2,
      "jobsalary_sum": 35,
      "materials_sum": 13.9,
      "meh_sum": 3.5,
      "total": 52.4,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "83",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Rūpnīiciski izolēta freona caurule Ø9.52",
      "info": "",
      "unit": "m",
      "quantity": 35,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 2.6,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 6.45,
      "workload_sum": 7,
      "jobsalary_sum": 122.5,
      "materials_sum": 91,
      "meh_sum": 12.25,
      "total": 225.75,
      "total_": ""
    },
    {
      "SystemID": 2.1,
      "system": "Apkure, ventilācija, dzesēšana",
      "ID": "84",
      "category": "KLIMATA KONTROLES SISTĒMA",
      "device": "K2",
      "description": "Rūpnīiciski izolēta freona caurule Ø12.7",
      "info": "",
      "unit": "m",
      "quantity": 30,
      "quantity_": "",
      "timerate": 0.2,
      "workrate": 17.5,
      "jobsalary": 3.5,
      "jobsalary_": "",
      "materials": 2.19,
      "materials_": "",
      "meh": 0.35,
      "meh_": "",
      "job_mat_meh": 6.04,
      "workload_sum": 6,
      "jobsalary_sum": 105,
      "materials_sum": 65.7,
      "meh_sum": 10.5,
      "total": 181.2,
      "total_": ""
    },
  ]};

  export default positions;